export const coronavirus = [
  "Asymptomatic",
  "Cluster",
  "Community spread",
  "Coronavirus",
  "COVID-19 (Coronavirus Disease 2019)",
  "Drive-thru testing",
  "Droplet transmission",
  "Endemic ",
  "Epidemic",
  "Flattening the curve",
  "Hand hygiene",
  "Incubation period",
  "Isolation",
  "N95 respirator",
  "Outbreak",
  "Pandemic",
  "Personal protective equipment (PPE)",
  "Preventing COVID-19",
  "Quarantine",
  "SARS (Severe acute respiratory syndrome)",
  "SARS-CoV-2 (Severe acute respiratory syndrome coronavirus 2)",
  "Self-isolation",
  "Self-monitoring",
  "Shelter-in-place order",
  "Social distancing",
  "Super-spreader",
  "Transmission",
  "Vaccine",
  "Ventilator",
];
