export const juryCharge = [
  "are you familiar",
  "Are you familiar with",
  "are you familiar with that",
  "are you familiar with the",
  "are you familiar with this",
  "as a matter of law",
  "at any time",
  "at that time",
  "bear in mind",
  "beyond a reasonable doubt",
  "burden of proof",
  "circumstantial evidence",
  "contributory negligence",
  "court and jury",
  "court reporter",
  "cross-examination",
  "direct evidence",
  "direct examination",
  "district attorney",
  "essential element",
  "for example",
  "for instance",
  "for the record",
  "from time to time",
  "gentlemen of the jury",
  "grand jury",
  "habeas corpus",
  "if anything",
  "if you believe",
  "in a minute",
  "in accordance",
  "in addition",
  "in any event",
  "in effect",
  "in evidence",
  "in fact",
  "in my opinion",
  "in order",
  "in other words",
  "in your opinion",
  "is it fair to say",
  "Is it to your understanding",
  "is it your opinion",
  "is that",
  "is that correct",
  "is that fair to say",
  "is that he",
  "is that I did",
  "is that I had",
  "is that right",
  "Is that so",
  "is that this",
  "is that true",
  "is that you",
  "is that you have",
  "is that you want",
  "is that your",
  "is that your opinion",
  "is that your recollection",
  "is that your signature",
  "is that your understanding",
  "is there a",
  "is there any evidence",
  "is there ever",
  "is there evidence",
  "is this the",
  "is this your signature",
  "isn’t that a fact",
  "isn’t that correct",
  "isn’t that right",
  "isn’t that so",
  "isn’t that true",
  "jury charge",
  "jury room",
  "just a minute",
  "ladies and gentlemen",
  "ladies and gentlemen of the jury",
  "law enforcement officer",
  "matter of law",
  "members of the jury",
  "more or less",
  "Mr. Foreman",
  "of course",
  "on or about",
  "on the other hand",
  "period of time",
  "police department",
  "police officer",
  "prejudice or sympathy",
  "preponderance of the evidence",
  "proximate cause",
  "prudent person",
  "reasonable degree",
  "refresh your recollection",
  "scene of the accident",
  "speed limit",
  "thank you",
  "that is correct",
  "that is right",
  "that’s true",
  "took place",
  "under the circumstances",
  "United",
  "United states of America",
  "wait a minute",
  "what",
  "with regard",
  "would you have remembered",
  "would you have remembered the",
  "yes or no",
  "your Honor",
];
