export const shortPhrases = [
  "Ladies and gentlemen of the jury",
  "Are you now or have you ever",
  "In the matter of",
  "In your own words",
  "Would you rephrase the question",
  "What is your business or occupation",
  "Do you have an opinion",
  "I am sure",
  "no longer",
  "not really",
  "I don't know",
  "Do you know",
  "Do you",
  "Do you believe",
  "don’t you believe the",
  "do you believe these",
  "do you believe those",
  "do you ever",
  "did you ever go",
  "do you feel",
  "do you ever go",
  "do you mean",
  "as far as",
  "I don't",
  "I can't",
  "I didn't",
  "I couldn't",
  "we can't",
  "we don't",
  "we didn't",
  "we couldn't",
  "going go",
  "you can't",
  "you don't",
  "you didn't",
  "you couldn't",
  "they couldn't",
  "they didn't",
  "they don't",
  "try to",
  "tries to",
  "trying to",
  "tried to",
  "familiar with",
  "in connection with",
  "when did",
  "could you",
  "can you",
  "did you ever go",
  "would you",
  "we don't believe",
  "we didn't see",
  "they can't see",
  "they don't see",
  "they couldn't believe",
  "they have",
  "they were",
  "they can't see",
  "they can't",
  "there were",
  "there have",
  "there was",
  "there could",
  "there couldn't",
  "did you see",
  "did I know",
  "I was",
  "you were",
  "if I could",
  "if she could",
  "if you should",
  "when you saw",
  "when you knew",
  "when you went",
  "sure you could",
  "whether you could",
  "with them",
  "with that",
  "with this",
  "we knew",
  "familiar with the",
  "tried to get",
  "trying to remember",
  "familiar with the",
  "in connection with those",
  "when did you know",
  "could you say",
  "can you believe",
  "did you know",
  "did you see",
  "would you say",
  "when you say",
  "he said",
  "she says",
  "they didn't go",
  "I didn't have",
  "if you would",
  "if he wouldn't",
  "you should",
  "they shouldn't",
  "when you did",
  "he didn't",
  "I was",
  "she wasn't",
  "did you see",
  "in as far as I know",
  "as far as you knew",
  "whether or not you agree",
  "did you recognize",
  "if you get",
  "sure he got",
  "when you went",
  "do you believe",
  "whether or not the",
  "when you are",
  "where you were",
  "don you want",
  "do you expect",
  "if you need",
  "as far as I understand",
  "I understood",
  "with that",
  "is this",
];
