export const phrases = [
  "a little bit\n",
  "a lot of\n",
  "a lot of the\n",
  "about me\n",
  "about the\n",
  "above and beyond the \n",
  "above and beyond the call of duty\n",
  "across the\n",
  "against the\n",
  "against the law of \n",
  "against the law of the\n",
  "against the law of the state\n",
  "against the law of the state of\n",
  "all of\n",
  "all of the\n",
  "all the\n",
  "along the\n",
  "among the\n",
  "and a\n",
  "and he\n",
  "and he is\n",
  "and he saw\n",
  "and he wasn't\n",
  "and he will\n",
  "and I\n",
  "and I go\n",
  "and I go to\n",
  "and I go to the\n",
  "and I saw\n",
  "and I wasn't\n",
  "and it\n",
  "and me\n",
  "and my\n",
  "and of\n",
  "and on\n",
  "and on the\n",
  "and so\n",
  "and the\n",
  "and us\n",
  "and wasn't\n",
  "and what is your occupation\n",
  "and will\n",
  "and will you rephrase the question\n",
  "and you\n",
  "and you saw\n",
  "and you will\n",
  "any of the\n",
  "are you now or have you ever\n",
  "as a\n",
  "as a matter of fact\n",
  "as a matter of law\n",
  "as far as\n",
  "as far as I know\n",
  "as far as I understand\n",
  "as far as you knew\n",
  "as he\n",
  "as I\n",
  "as it\n",
  "as of \n",
  "as the\n",
  "as well as\n",
  "as you\n",
  "ask the\n",
  "ask you\n",
  "at a\n",
  "at a time\n",
  "at that time\n",
  "at the\n",
  "at the time\n",
  "at this point\n",
  "at this time\n",
  "aware of\n",
  "aware of the\n",
  "based on\n",
  "because a\n",
  "because of the\n",
  "because the\n",
  "been a \n",
  "before an\n",
  "believe me\n",
  "best of my knowledge\n",
  "between you and me\n",
  "both of\n",
  "both of us\n",
  "but he\n",
  "but I\n",
  "but it\n",
  "but it's \n",
  "but the\n",
  "but you\n",
  "calls for legal conclusion\n",
  "can I\n",
  "can they\n",
  "can you\n",
  "can you believe\n",
  "can you say\n",
  "can you tell\n",
  "can you tell me\n",
  "can you tell us\n",
  "cause of the accident\n",
  "cease and desist\n",
  "cease and desist order\n",
  "conclusions of law\n",
  "could assume a fact not in evidence\n",
  "could they\n",
  "could you\n",
  "could you say\n",
  "could you tell me\n",
  "day after\n",
  "day before\n",
  "did I know\n",
  "did they\n",
  "did you ever go\n",
  "did you go\n",
  "did you go to\n",
  "did you go to the\n",
  "did you know\n",
  "did you recognize\n",
  "did you see\n",
  "discovery of admissible evidence\n",
  "do a\n",
  "do they\n",
  "do you \n",
  "do you believe\n",
  "do you believe the\n",
  "do you believe these\n",
  "do you believe those\n",
  "do you ever\n",
  "do you ever go\n",
  "do you expect\n",
  "do you feel\n",
  "Do you have an opinion \n",
  "do you have any reason to believe\n",
  "do you know\n",
  "do you mean\n",
  "do you want\n",
  "drive under the influence\n",
  "drives under the influence\n",
  "driving under the influence\n",
  "dropped out of the\n",
  "duly licensed \n",
  "duly licensed to practice\n",
  "duly licensed to practice in the state of\n",
  "during the\n",
  "each and every\n",
  "each and every element\n",
  "each and every on of the\n",
  "each and every one\n",
  "each and every one of these\n",
  "each and every one of those\n",
  "enough of\n",
  "enough of the\n",
  "enough of them\n",
  "enough of these\n",
  "enough of those\n",
  "familiar with\n",
  "familiar with the\n",
  "for a \n",
  "for how long\n",
  "for the record\n",
  "from a\n",
  "from me\n",
  "from my\n",
  "from the\n",
  "get me\n",
  "get the\n",
  "give me\n",
  "going to  \n",
  "got the\n",
  "greater weight of the evidence\n",
  "guilty or innocent\n",
  "guilty or not guilty\n",
  "had an \n",
  "had the\n",
  "had they\n",
  "had you ever\n",
  "had you ever been\n",
  "had you ever been the\n",
  "has a\n",
  "has the\n",
  "have the\n",
  "have you ever been convicted of a felony\n",
  "have you ever had your deposition taken\n",
  "have you ever had your deposition taken before\n",
  "have you remembered\n",
  "have you remembered the\n",
  "he\n",
  "he didn't\n",
  "he is\n",
  "he said\n",
  "he saw\n",
  "he wasn't\n",
  "he will\n",
  "here\n",
  "here with\n",
  "here's a\n",
  "here's the\n",
  "he's a\n",
  "he's the\n",
  "how many of those\n",
  "I am sure\n",
  "I can't\n",
  "I couldn't\n",
  "I didn't \n",
  "I didn't have\n",
  "I don't\n",
  "I don't \n",
  "I don't have\n",
  "I don't know\n",
  "I don't remember\n",
  "I don't see\n",
  "I don't think\n",
  "I don't want\n",
  "I go\n",
  "I go to the\n",
  "I mean\n",
  "I need to\n",
  "I saw\n",
  "I say\n",
  "I see\n",
  "I show you what has been marked\n",
  "I show you what has been marked as\n",
  "I show you what's been marked\n",
  "I show you what's been marked as\n",
  "I think the\n",
  "I understood\n",
  "I was\n",
  "I wasn't\n",
  "I will\n",
  "if a \n",
  "if he wasn't\n",
  "if he wouldn't\n",
  "if I could\n",
  "if I wasn't\n",
  "if she could \n",
  "if the\n",
  "if they\n",
  "if you get\n",
  "if you go\n",
  "if you go to\n",
  "if you go to the\n",
  "if you have remembered \n",
  "if you have remembered the\n",
  "if you need\n",
  "if you saw\n",
  "if you should\n",
  "if you would\n",
  "I'll show you what's been marked\n",
  "I'll show you what's been marked as\n",
  "I'm going to\n",
  "in a \n",
  "in connection with\n",
  "in connection with those\n",
  "in object to the form of the question\n",
  "in terms of\n",
  "in terms of the\n",
  "in the\n",
  "in the matter of\n",
  "in your own words\n",
  "instead of\n",
  "is a\n",
  "is he\n",
  "is it \n",
  "is it the\n",
  "is it your opinion\n",
  "is the\n",
  "is this\n",
  "it is a \n",
  "it says\n",
  "it wasn't\n",
  "it will\n",
  "it's a\n",
  "it's a \n",
  "it's the\n",
  "kind of\n",
  "kinds of\n",
  "ladies and gentlemen of the jury\n",
  "lead to discovery of admissible evidence\n",
  "let me\n",
  "let me help you stop \n",
  "let me help you stop there\n",
  "life insurance policy\n",
  "looking at\n",
  "lot of\n",
  "lots of\n",
  "made a \n",
  "majority of\n",
  "majority of the\n",
  "make a\n",
  "make sure that\n",
  "many of\n",
  "many of the\n",
  "may we approach the bench\n",
  "may we approach the bench, your Honor\n",
  "most of\n",
  "most of the\n",
  "my name is \n",
  "my opinion\n",
  "no longer\n",
  "no matter\n",
  "no matter what\n",
  "not really\n",
  "not to my knowledge\n",
  "not to my recollection\n",
  "number of\n",
  "of a \n",
  "of it\n",
  "of me\n",
  "of the\n",
  "on a \n",
  "on it\n",
  "on the\n",
  "on the part of\n",
  "on the part of the\n",
  "one of the\n",
  "or the\n",
  "out of\n",
  "out of pocket\n",
  "out the\n",
  "out-of-pocket\n",
  "pardon me\n",
  "part of\n",
  "part of the\n",
  "parts of\n",
  "parts of the\n",
  "please state your full name for the record\n",
  "preponderance of the evidence\n",
  "prior to that accident\n",
  "prior to the accident\n",
  "prior to this accident\n",
  "prior to your accident\n",
  "put the\n",
  "referring to\n",
  "say your name\n",
  "scene of that accident\n",
  "scene of the accident\n",
  "she go\n",
  "she goes\n",
  "she goes to\n",
  "she is the\n",
  "she says\n",
  "she wasn't\n",
  "she's a\n",
  "she's the\n",
  "since the accident\n",
  "slip-and-fall accident\n",
  "so I can\n",
  "so it\n",
  "so the\n",
  "so they\n",
  "some of the\n",
  "sort of\n",
  "sorts of\n",
  "spell it for the record\n",
  "state of\n",
  "state your\n",
  "state your business\n",
  "state your full name\n",
  "state your full name and spell it for the record\n",
  "state your name\n",
  "state your name and address\n",
  "state your name for the record\n",
  "state your opinion\n",
  "talking about\n",
  "tell me\n",
  "tell the\n",
  "tell us\n",
  "tell you\n",
  "that accident\n",
  "that he had\n",
  "that he has\n",
  "that he saw\n",
  "that is the\n",
  "that wasn't\n",
  "that you can\n",
  "that you saw\n",
  "that’s not my question\n",
  "that's a\n",
  "the accident\n",
  "the company\n",
  "the last time\n",
  "then they\n",
  "there could\n",
  "there couldn't\n",
  "there have\n",
  "there was\n",
  "there were\n",
  "they can't\n",
  "they can't see\n",
  "they couldn't\n",
  "they couldn't believe\n",
  "they didn't\n",
  "they didn't go\n",
  "they don't\n",
  "they don't see\n",
  "they go\n",
  "they go to\n",
  "they go to the\n",
  "they have\n",
  "they shouldn't\n",
  "they were\n",
  "this accident\n",
  "this is the\n",
  "through me\n",
  "through my\n",
  "time of the accident\n",
  "to a \n",
  "to be honest\n",
  "to do\n",
  "to do so\n",
  "to go to\n",
  "to it\n",
  "to make sure\n",
  "to me\n",
  "to my\n",
  "to say\n",
  "to the\n",
  "to us\n",
  "to you\n",
  "told me\n",
  "told you\n",
  "tried to\n",
  "tried to get\n",
  "tries to\n",
  "try to\n",
  "trying to\n",
  "trying to remember\n",
  "type of\n",
  "wanted to\n",
  "we can't\n",
  "we couldn't\n",
  "we didn't\n",
  "we didn't see\n",
  "we don't\n",
  "we don't believe\n",
  "we go\n",
  "we go to\n",
  "we go to the\n",
  "we knew\n",
  "we saw\n",
  "were they\n",
  "what a n\n",
  "what is the\n",
  "what is your business or occupation\n",
  "what kind of\n",
  "what my\n",
  "what the\n",
  "what they\n",
  "when a\n",
  "when did\n",
  "when did you know\n",
  "when the\n",
  "when you are\n",
  "when you did\n",
  "when you go\n",
  "when you go to\n",
  "when you go to the\n",
  "when you knew\n",
  "when you saw\n",
  "when you say\n",
  "when you went\n",
  "where he got\n",
  "where I wasn't\n",
  "where is the\n",
  "where the\n",
  "where they\n",
  "where you could\n",
  "where you go\n",
  "where you go to\n",
  "where you go to the\n",
  "where you were\n",
  "whether me\n",
  "whether my\n",
  "whether or not the\n",
  "whether or not you agree\n",
  "whether or not you are able to\n",
  "whether they\n",
  "whether you saw\n",
  "which is the\n",
  "which the\n",
  "which they\n",
  "who is the\n",
  "who saw\n",
  "why is the\n",
  "why they\n",
  "with a \n",
  "with me\n",
  "with my\n",
  "with that\n",
  "with the\n",
  "with them\n",
  "with this\n",
  "would they\n",
  "would you\n",
  "would you please describe the\n",
  "would you rephrase the question\n",
  "would you say\n",
  "would you take a look\n",
  "would you take a look at\n",
  "would you take a look at the\n",
  "would you tell me\n",
  "would you understand\n",
  "would you understand the\n",
  "you  should\n",
  "you are able to say\n",
  "you can't\n",
  "you couldn't\n",
  "you didn't\n",
  "you don't \n",
  "you don't have\n",
  "you don't know\n",
  "you don't recall\n",
  "you don't remember\n",
  "you go \n",
  "you go to\n",
  "you go to the\n",
  "you have a right to remain silent\n",
  "you know what I mean\n",
  "you know what I'm saying\n",
  "you saw\n",
  "you say\n",
  "you see\n",
  "you were\n",
  "you will\n",
];
